[package]
name = "steviegoodman/unnamed-project"
description = "No description provided."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Hitbox = "breezy1214/hitbox@4.1.2"
Packet = "rajden28/suphi-packet-main@1.7.1"